REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (1,'HHM','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (2,'Individual Details','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (3,'Programs','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (4,'Modes','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (5,'Pregiram Request','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (6,'Relationship Details','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (7,'Interview Details','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (8,'Education Details','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (9,'Living Arrangement','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (10,'Citizenship','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (11,'Out of State Benefit','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (12,'Disability','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (13,'Special Medical Approval','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (14,'Pregnancy','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (15,'Tax Information','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (16,'Room and Board details','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (17,'Non custodial parent','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (18,'Liquid Asset','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (19,'Vehicle Asset','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (20,'Burial Asset','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (21,'Other Asset','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (22,'Livestock asset','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (23,'Compliance','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (24,'Earned Income','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (25,'Unearned Income','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (26,'Self Employment Income','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (27,'MAGI Income','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (28,'Dependent Care Expense','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (29,'Medical expense','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (30,'Child Support and Alimony Expense','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (31,'MAGI Expense','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (32,'Shelter Expense','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (33,'Utility Expense','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (34,'Other Expense','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (35,'Eligibility Results','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (36,'Filing Unit','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (37,'Budget Summary','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (38,'Missing Verification','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (39,'Authorization','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (40,'Notices','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (41,'Appeal Create','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (42,'Appeal Maintain','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (43,'Dismissal ','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (44,'Task','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (45,'HIP Pay/No Pay Screen','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (46,'Comments/Additonal check can be added','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (47,'SCH-Office','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (48,'SCH-Date to be selected','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (49,'SCH-Appointment Type','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (50,'SCH-Appointment Status','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (51,'SCH-Application Registration','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (52,'SCH-File Clearance','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (53,'SCH-Application Type','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (54,'SCH-DC','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (55,'SCH-Schedule Interview','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (56,'SCH-Interview Method','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (57,'SCH-Search Appontment','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (58,'SCH-Edit Apppointment ','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (59,'SCH-View and maintain Appointment','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (60,'SCH-View Calendar','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (61,'SCH-Create Activity','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (62,'SCH-View Activity','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (63,'SCH-Delete Activity','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (64,'Application Dispostion','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (65,'Case Association','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (66,'Application Registration-Validation check','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (67,'DC- validation check','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (68,'Individual Filing Taxes and  Individual Required To File Taxes ','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (69,'Withdraw program','TestDescFromCode','Y');
Insert into EXPORT_TABLE (ID,CATEGORY_NAME,CATEGORY_DESC,ACTIVE_SW) values (70,'Fuzzy Search Value','TestDescFromCode','Y');
