REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (1,'DC - Revert To Open','Create a SNAP denied case by providing earned income higher than income standards and authorize the case. Reopen the same case in Revert To Open mode','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (2,'DC - Revert To Open TANF','Create a TANF denied case by providing unearned income higher than income standards and authorize the case. Reopen the same case in Revert To Open mode','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (3,'DC - Revert To Open MA','Create a MA denied case by providing MAGI income higher than income standards and authorize the case. Reopen the same case in Revert To Open mode','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (4,'DC - SNAP - 1 Household','Create a SNAP case with 1 household individuals
Verify the task creation - 
T0015 - Trust Information Review for Legal
T0039 - Authorize Override','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (5,'DC - TANF - 3 Household','Create a TANF case with 3 household individuals. 
Verify the task creation - T0007 - Sanction or Penalty added or changed','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (6,'SMK - SNAP 2 HH','Create a SNAP 2Household case and authorize the case. Edit the case in case change mode and rerun eligibity.
Verify the SNAP Approval Correspondence
Verify the task creation - T0001 - No interview scheduled-SNAP or Cash Application ','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (7,'SCH_TC_009_AutoApptExpSNAPWithoutMA','Submit an application for expedited SNAP without MA and schedule an auto appointment of type Expedited SNAP without MA','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (8,'SCH_TC_006_AutoApptWithSNAP','Create a SNAP application with one member and schedule an appointment.
Verify the appointment and delete it.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (9,'SCH_TC_007_AutoApptWithoutSNAP','The intent of the scenario is to schedule an appointment for an application. Further search for the it and delete it. Each step involves verification after every action.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (10,'SCH_TC_010_AutoApptResAssessment','Create a all program application with one member and schedule an appointment.
Verify the appointment and delete it.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (11,'SCH_TC_002_ARManuallyScheduleAppt','The intent of the scenario is to schedule an appointment for an application. Further search for the it, edit it and cancel it. Each step involves verification after every action.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (12,'SCH_TC_001_ScheduleManualAppt','The intent of the scenario is to schedule a manual appointment for an application with SNAP. Further search for the it, edit it and cancel it. Each step involves verification after every action.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (13,'R56_TC005_WorkforceAttachment','The purpose of this scenario is to validate that MADW is not formed when the individual is disabled and is not working or attached to the workforce.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (14,'INT - SNAP - 17 3 Household Aliens Eligible','The purpose of this test case is to validate that an approved alien is Eligible for SNAP benefits. Create a 3-person household consisting of two individuals who are Conditional Entry aliens, living with a Sibling who is a US Citizen. The Sibling has a vehicle that should be counted and the mother has countable earned income and a countable liquid asset.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (15,'R4C_SNAP_TC011','The objective of this test case is to validate that a roomer  is Excluded from the SNAP AG when the following conditions are true: 
1. Individual Does NOT purchase or prepare with the SNAP Primary Individual
2. Individual claims roomer status
Post Condition:
1. Identify Individual as ineligible
2. Set notice reason = Individual is a roomer
3. Set notice reason = Individual does not purchase and prepare together
4. Exclude Individual from the Assistance Unit and the Filing Unit','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (16,'R6_TC061_TMA','Validate TMA after adding child to existing TMA eligible mother','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (17,'INT_HCHIP_TC002_MASI','The purpose of this test case is to validate if an MASI AG is created for the Individual who is receiving SSI and is disabled.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (18,'R7_TC028_CR596214_015','Validate that in case change after an year MARP benefits are closed and MASP are given for an individual requesting health care coverage and has a monthly income of wages of 800$.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (19,'R4C_SNAP_TC025','The purpose of the test case is to validate that  the core SNAP Assistance Group, based on purchase and prepare with the SNAP Primary Individual and/or spouse and child(ren) relationship to the SNAP Primary Individual, is formed. 

The Spouse, Child <22, and Spouse''s Child <22 should be included in the AG when they do not Purchase and Prepare with the SNAP PI. 

PSD: 3.2.3.08; #6, 8 , 12, 

Post Condition:
Individual should be Included in the Assistance Unit','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (20,'MO_TC006_143686','Register an application for an individual requesting health care coverage, age 70 having Special Medicaid Approvals,Liquid Assets of type Cash($13200.00) and have the resource transfer for the same 59 months ago and Vehicle Assets of value $5000.00 and have the resource trasnfer for the same 12th of last month .Veify that on running ED ASSISTANCE GROUP IS INELIGIBLE DUE TO TRANSFER OF RESOURCES is set and individual is not eligble for Health care.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (21,'Reason Codes - EL0318','The intent of the scenario is to verify the reason code message for PI is "FISCAL SANCTION CONTINUES DUE TO PRA - D/S ABUSE"','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (22,'R7_TC007_FormerFosterChildren','Verify the worker is eligible for MA 15 as individual is indiana Resident.
Verify a validation error message is not thrown and the worker is allowed to close the MA 15 AG when the AG is failing due to the reason code ''NOT AN INDIANA RESIDENT''.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (23,'R7_TC027_CR596214_008','Validating the Application and Semi annual review dates.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (24,'R7_TC027_CR596214_008','Validating the Recert review due dates.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (25,'R7_TC027_CR596214_008','Validate ED_CASE_RECERT_DATES table with case number and validate none of the program are recertified for next 12 month.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (26,'R6_TC053_TMA','Validate the MA filing unit for all the individuals and Authorize the case also validate the No Correspondence notice is Generated for Today on View pending screen','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (27,'R6_TC053_TMA','Validate the MA filing unit for all the individuals and Authorize the case.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (28,'R6_TC053_TMA','Validate the authorization status as “Authorized”.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (29,'R6_TC053_TMA','Increase the income and validate MASP should be eligible','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (30,'R6_TC053_TMA','Validate the Hip Information in Medicaid - Filing Unit Summary also verify the authorization status as “Not Authorized”. Authorize the case.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (31,'R6_TC053_TMA','Validate the MA filing unit for all the individuals and Authorize the case also validate the No Correspondence notice is Generated for Today on View pending screen.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (32,'Reason Codes - EL0308','Create a TANF case (parent and child) with Non-Compliance type = Child - School attendance not met and the notice reason should be ''CHILD FAILED TO COMPLY WITH SCHOOL ATTENDANCE REQUIREMENT''','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (33,'R6_TC049_TMA','Validate that the TMA Indicator is set to "No" for an individual who was Eligible for MARP and has the low-income indicator set for 3 of the last 6 months has an increase in earned income less than 133% FPL.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (34,'R6_TC049_TMA','Validate that the TMA Indicator is set to "No" for an individual who was Eligible for MARP and has the low-income indicator set for 3 of the last 6 months has an increase in earned income less than 133% FPL.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (35,'R6_TC049_TMA','Validate that the TMA Indicator is set to "No" for an individual who was Eligible for MARP and has the low-income indicator set for 3 of the last 6 months has an increase in earned income less than 133% FPL.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (36,'R6_TC049_TMA','Validate that the TMA Indicator is set to "No" for an individual who was Eligible for MARP and has the low-income indicator set for 3 of the last 6 months has an increase in earned income less than 133% FPL.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (37,'R6_TC036_TaskTrigger_Day0,R6_TC036_TaskTrigger_Day1','The intent of the scenarios is to verify the end to end funcionality of State Review of Eligibility Determination task flow.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (38,'AR_TC_001_ApplicationRegistrationScreens_1','The intent of the scenario is to check the flow of application disposition flow of application registration. ','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (39,'AR_TC_001_ApplicationRegistrationScreens_2','The intent of the scenario is to check the case association functionality in AR flow.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (40,'AR_TC_001_ApplicationRegistrationScreens_3','The intent of the scenario is to check for validation messages on AR screens.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (41,'R7_017_RTOD_CR570188_day0','To verify missing verification and review due dates for snap','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (42,'R7_017_RTOD_CR570188_semi_annual','To verify missing verification and review due dates for snap','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (43,'R7_017_RTOD_CR570188_annual review','To verify missing verification and review due dates for snap','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (44,'INT - SNAP - 12 Parolle Ineligible Denied','Create a 1 mm hh requesting for SNAP, in the household and in home. Enter Citizenship as Alien and immigration status as Parolee.Asset test should be fail and income test should be Pass.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (45,'R4C_SNAP_TC001','Create a 2 mm hh requesting for SNAP, relationship is Other – Related, living in home and US citizens. Enter room and Board details for the Non PI member, type Boarder paid to PI , 199$ monthly. Run Ed and SNAP should be eligible with AU size as 2. Authorize the case. Open the case in Case Change mode andupdate address','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (46,'R6_TC057_TMA_Day0','Create a 2 mm  household- parent and child.verify TOA as MASP for PI eligible and TOA MA 2 for child eligible and authorize the case.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (47,'R6_TC057_TMA_Day1','open the case in case change mode and authorize it','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (48,'R6_TC057_TMA_Day122','Open the case on case change mode on today+122 days and  Edit the earned income and update amt to 2050$. Edit the Magi income and update amt to 2050$. Run ED and verify TOA as MASP for PI eligible and TOA MA for child eligible and authorize the case.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (49,'R6_TC057_TMA_Day0','Open the case in add person mode and add spouse of PI requesting Medicaid filing tax jointly, in home and US citizen. Run Ed and verify TOA as MASP for PI eligible and TOA MA for child eligible and  TOA MARP  for new spouse .Authorize the case.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (50,'R7_TC005_FormerFosterChildren','Create a 2 mm hh requesting Medicaid father and son. Do case change and withdraw program.validate DI1322: \"Closure action not allowed. Individual ''~'' in ''Foster Care''. ''Former Foster Care'' or ''Adoption Assistance'' and age less than 26 years is Generated on authorization','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (51,'Scheduling - Automatic Appt with SNAP','Create a SNAP application with one member and schedule an appointment.
Verify the appointment and delete it.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (52,'R4C_SNAP_TC035','Create a 4HH snap eligible case and verify the ED results and FU','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (53,'INT_HCHIP_TC003_MANA_Day00_01','A 1HH HCC case is created and self employment income – wages is added to the case and authorized.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (54,'Scheduling - Follow Up Impact Appointment','To schedule a follow-up impact meeting for a SNAP case with 2HH (parent-child). If the appointment is conflicting, another appointment is scheduled and already created one is deleted.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (55,'SMK - SNAP 2 HH','2 mm husband and wife for snap/cash assistance. Submit the application and check No interview scheduled - SNAP or Cash Application task is created. DC- In the household. Enter room board details for husband. Liquid assets husband, savings account of 50$, unearned income Other - Non-Exempt of 200$, medical expense of dental care to husband of 25$, run ed- snap eligible AU is 2. Authorize the case.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (56,'SMK - TANF 2 HH','Create a 2 mm hh for tanf parent and child.in home. Parent is disabled. Case Is eligible for tanf.Open case in cc mode and verify Eligibility Notice for TANF – Approval is generated.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (57,'SMK - MA 2 HH','2 mm hh parent child for Medicaid. Enter assets- livestock of 50$. Enter magi income for father of 800$.utility exp for father of 40$. Run Ed. MA z for child is eligible and MA l for parent is eligible. Authorize the case. Open the case in cc mode and verify Eligibility Notice for Health Coverage - ApprovalIs generated.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (58,'INT - HC & HIP - 0045 MASP & MA 2','to validate that the Eligibility Status is pending for the individual whose Date of Birth is Unverified.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (59,'R6_TC056_TMA','Validate half siblings are included in the TMA group with the magnet child.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (60,'R6_TC056_TMA','Validate half siblings are included in the TMA group with the magnet child in Case Change mode','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (61,'R6_TC056_TMA','Validate half siblings are included in the TMA group with the magnet child in Case Change mode with change in income.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (62,'INT - SNAP - 6 Alien-LAPR Eligible','The purpose of this test case is to validate that an approved alien is Eligible for SNAP benefits.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (63,'MO_TC001_142965','Transitioning of TOA from MA 9 to MARB to MARP','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (64,'INT_SNAP_TC_058','Verify notice PENDING VERIFICATIONS FOR APPLICANTS/RECIPIENTS when household questions are marked Pend due to which snap case pends','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (65,'R56_TC002_CO_IED100_V5S','Verify  Spanish notices for IED100 V5 -  HIP Approval_State Plan Plus Native American','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (66,'R56_TC001_CO_IED100_V3E','Verify  english notices for IED100 V3 -  HIP Approval_Regular Plus Native American','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (67,'RC_TC014_EL1003','. Verify on FU summary for TANF and verify that FAILURE TO SIGN A PERSONAL RESPONSIBILITY AGREEMENT is displayed as the reason code for parent if parent has failed to sign PRA','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (68,'R6_TC034_AllowWorkerClosure','Validate that the user is able to authorize the closure of a CE child of age < 3 years old with the acceptable reason "ASSISTANCE GROUP MOVED TO ANOTHER CASE". 
No validations should be displayed.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (69,'R6_TC034_AllowWorkerClosure','Validate that the user is able to authorize the closure of a CE child of age < 3 years old with the acceptable reason "ASSISTANCE GROUP MOVED TO ANOTHER CASE". 
No validations should be displayed.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (70,'R6_TC034_AllowWorkerClosure','Validate that the user is able to authorize the closure of a CE child of age < 3 years old with the acceptable reason "ASSISTANCE GROUP MOVED TO ANOTHER CASE". 
No validations should be displayed.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (71,'INT - SNAP - 59 Expedited','The Purpose of this test case is to validate that the case is Authorized for SNAP - Expedited application for a two household composition consisting Husband and Wife','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (72,'R4C_SNAP_TC041','Group should be identified as "HOMELESS" when the Homeless Individual is the SNAP Primary Individual and the Individual''s living arrangement is homeless / homeless shelter.

Post Condition:
1. Group should be identified as Homeless when  the PI is homeless','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (73,'R7_TC024_CR596214_RedetE2E','Redetermination End to End Scenario','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (74,'R7_TC024_CR596214_RedetE2E','Redetermination End to End Scenario','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (75,'R7_TC024_CR596214_RedetE2E','Redetermination End to End Scenario','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (76,'R56_TC012_MRTDeniedClosed','The objective of this test case is to validate that the Reason Code EL0348 displays on the EDBC screens and correspondences when the MRT Determination is Denied.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (77,'R56_TC012_MRTDeniedClosed','The objective of this test case is to validate that the Reason Code EL0348 displays on the EDBC screens and correspondences when the MRT Determination is Denied.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (78,'R6_TC027_ExtendSuspensionPeriod','The purpose of this test case is to validate text changes implemented in IED090_V3 Spanish notice','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (79,'R6_TC027_ExtendSuspensionPeriod','The purpose of this test case is to validate text changes implemented in IED090_V3 Spanish notice','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (80,'R6_TC028_ExtendSuspensionPeriod','The purpose of this test case is to validate text changes implemented in IED090_V6 English notice.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (81,'R6_TC035_DiscIndLowIncome','The purpose of this test case is to verify below information''s when 19 yr. old applies for fast track HC.
-- MARP - fully Eligible AG forms with $1 PAC for 19 yr. old.
-- LOW INCOME 19/20 YEAR OLD switch is not marked Yes..
-- HIP Approval notice is generated.
-- Interface sends LOW INCOME 19/20 YEAR OLD indicator in CDEE file as ''N''.  ','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (82,'R6_TC026_ExtendSuspPeriod','The purpose of this test case is to validate text changes implemented in IED090_V1 and IED089_V1 English notices.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (83,'RC_TC018_EL3007','To verify the correct notice reason when income is more than 130% gross income standard in an ongoing SNAP case','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (84,'R56_TC004_CO_IED095_V14S','Verify  Spanish notices for  Eligibility Notice for Health Coverage - HIP Conditional Approval','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (85,'MO_TC009_144778','Validate the Mailer due date and Verify the Eligibility results MARP should be eligible. ','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (86,'R4C_401830 - MAI Intake English','The objective of this test case is to validate that T0486 is generated upon authorizing MA J. 
Notice should not be generated when the written language is English','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (87,'INT - SNAP - 29 Alien Sponsor','The Purpose of this test case is to validate that an alien Sponsor is included in the AG when the applicant chooses to include the individual on the application.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (88,'CO_TC_002_ViewHistory','Create a case and authorize the case. Create an non-eligibility appeal to create a Notice of Dismissal correspondence.
Validate the View History Correspondence Details.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (89,'R7_007_RTOD_CR570188','NA','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (90,'R6_TC055_TMA','Validate that If the TMA person gets pregnant, they will go to the pregnant category and they will not be TMA Eligible anymore. ','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (91,'R7_012_RTOD_CR570188','A 2 HH snap case is created with earned income wages. The case is eligible with AU as 2. Case is authorized and semi-annual review due date is verified.  Case is then opened in case change mode and person demographics details are updated . Ed is run again and status is verified and case is authorized. Eligibility status remains No change. Notice of Dimissal is then verfiied and finally recert review due date is verified.','Y',null,null);
Insert into EXPORT_TABLE (ID,SCENARIO_NAME,SCENARIO_DESC,ACTIVE_SW,REL_PATH,FILE_NAME) values (92,'Reason Codes - EL1010','desc-Dummy','Y',null,null);
